import fintechImg from '../assets/projects/fintech.svg'
import healthImg from '../assets/projects/health.svg'
import iotImg from '../assets/projects/iot.svg'
import mapImg from '../assets/projects/map.svg'
import mobileImg from '../assets/projects/mobile.svg'
import nextGenPlatformImg from '../assets/projects/next-gen-platform.svg'
import psaWorkflowImg from '../assets/projects/psa-function-replication.svg'
import signatureDemoImg from '../assets/projects/signature-demo.svg'
import universityImg from '../assets/projects/university.svg'
import webImg from '../assets/projects/web.svg'

export type ProjectCategory =
  | 'Fintech'
  | 'Platform'
  | 'Mobile'
  | 'Web'
  | 'IoT'
  | 'Logistics'
  | 'University'

export type Project = {
  id: string
  title: string
  timeframe: string
  org: string
  role: string
  teamSize: string
  category: ProjectCategory
  tagline: string
  highlights: string[]
  tech: string[]
  links?: {
    live?: string
    source?: string
    caseStudy?: string
  }
  image?: {
    src: string
    alt: string
    credit?: string
  }
  featured?: boolean
  responsibilities?: string[]
  metrics?: string[]
}

export const PROJECT_CATEGORIES: ProjectCategory[] = [
  'Fintech',
  'Platform',
  'Mobile',
  'Web',
  'IoT',
  'Logistics',
  'University',
]

const PROJECT_MONTH_INDEX: Record<string, number> = {
  jan: 0,
  feb: 1,
  mar: 2,
  apr: 3,
  may: 4,
  jun: 5,
  jul: 6,
  aug: 7,
  sep: 8,
  oct: 9,
  nov: 10,
  dec: 11,
}

function getProjectSortTime(timeframe: string) {
  const [startText = '', endText = ''] = timeframe.split(/\s+[–-]\s+/)
  const sortText = (endText || startText).trim()

  if (sortText.toLowerCase() === 'present') {
    return Number.MAX_SAFE_INTEGER
  }

  const [monthText = '', yearText = ''] = sortText.split(/\s+/)
  const month = PROJECT_MONTH_INDEX[monthText.slice(0, 3).toLowerCase()] ?? 0
  const year = Number.parseInt(yearText, 10)

  if (Number.isNaN(year)) return 0

  return Date.UTC(year, month, 1)
}

export const allProjects: Project[] = [
  {
    id: 'psa-tibco-to-java-modernization',
    title: 'PSA',
    timeframe: 'May 2026 – Jun 2026',
    org: 'FPT Software',
    role: 'Backend Engineer (Java)',
    teamSize: '',
    category: 'Logistics',
    tagline:
      'Supported migration validation by using an existing Function Replication testing tool to compare execution logs and business results between legacy TIBCO services and Java services.',
    highlights: [
      'Reduced Function Replication validation time from approximately half a day to around one hour.',
      'Improved migration testing productivity by approximately 75%.',
      'Provided clear comparison reports to help the team identify behavioral differences between legacy TIBCO and Java services.',
    ],
    tech: [
      'Java 21',
      'TIBCO',
      'Log Analysis',
      'Function Replication Testing',
      'Test Reporting',
      'Tool Optimization',
    ],
    links: {
      live: '',
      source: '',
      caseStudy: '',
    },
    image: {
      src: psaWorkflowImg,
      alt: 'Function Replication testing workflow comparison illustration',
    },
    featured: true,
    responsibilities: [
      'Executed an existing Function Replication testing tool to validate functional equivalence between legacy TIBCO services and Java services.',
      'Compared execution logs and business results generated by both systems.',
      'Analyzed mismatches and prepared validation reports for the migration team.',
      'Improved the existing Function Replication testing tool and workflow.',
    ],
  },
  {
    id: 'next-generation-fintech-aggregator-platform',
    title: 'Next-Generation Fintech Aggregator Platform',
    timeframe: 'Nov 2024 – May 2026',
    org: 'FPT Software',
    role: 'Backend Engineer (Java)',
    teamSize: 'Cross-functional',
    category: 'Fintech',
    tagline:
      'Production-grade digital lending backend enabling onboarding, eligibility, and credit approval across multiple UAE banks via shared rule + workflow core.',
    highlights: [
      'Built core credit decisioning services for credit limit assignment, DBR computation, and multi-product eligibility scoring.',
      'Designed and maintained a Drools rule engine for segmentation, filtration, and deviation handling in automated offer matching.',
      'Implemented limit assignment logic using finalized income, product configurations, and institutional constraints.',
      'Integrated AECB, FTS, and FinOne for financial and identity validation across underwriting flows.',
      'Orchestrated submission-to-approval journeys with Camunda BPM and real-time status updates.',
      'Hardened production readiness with monitoring, recovery controls, incident support, and performance tuning.',
    ],
    tech: [
      'Java 17',
      'Spring Boot',
      'REST API',
      'Microservices',
      'Drools',
      'Camunda BPM',
      'Oracle DB',
      'AWS',
      'Jenkins',
      'ArgoCD',
      'Git',
    ],
    links: {
      live: '',
      source: '',
      caseStudy: '',
    },
    image: {
      src: fintechImg,
      alt: 'Colorful banking and credit decisioning illustration',
    },
    featured: true,
    responsibilities: [
      'Designed backend domain flows for onboarding, decisioning, and approval orchestration.',
      'Maintained underwriting integrations with external financial data providers.',
      'Collaborated with QA, product, and operations during release and incident cycles.',
    ],
    metrics: [
      'Supported multi-bank reuse through a shared rules and workflow core.',
      'Improved operational visibility with production monitoring and recovery controls.',
    ],
  },
  {
    id: 'next-gen-platform',
    title: 'Next Gen Platform',
    timeframe: 'Mar 2024 – Oct 2024',
    org: 'FPT Software',
    role: 'Backend Engineer',
    teamSize: 'Cross-functional',
    category: 'Platform',
    tagline:
      'Microservices modernization for booking channels and driver apps with event-driven architecture and scalable cloud foundations.',
    highlights: [
      'Contributed to a microservices migration focused on secure, multi-tenant, and scalable platform behavior.',
      'Implemented OpenAPI improvements and event notifications through Kafka and ActiveMQ.',
      'Supported platform design alignment across teams on service boundaries and API standards.',
      'Built data integration pipelines using AWS Glue for downstream consumers.',
      'Worked through QA, UAT, go-live readiness, and operational handover activities.',
      'Improved SonarCloud coverage, logging quality, and release readiness practices.',
    ],
    tech: [
      'Java 17',
      'Spring Boot',
      'Microservices',
      'Kafka',
      'ActiveMQ',
      'OpenAPI',
      'PostgreSQL',
      'MongoDB',
      'AWS Glue',
      'Terraform',
      'Docker',
      'SonarCloud',
      'Git',
    ],
    links: {
      live: '',
      source: '',
      caseStudy: '',
    },
    image: {
      src: nextGenPlatformImg,
      alt: 'Event-driven booking platform modernization illustration',
    },
    featured: true,
    responsibilities: [
      'Implemented backend features across modernized booking and driver-facing services.',
      'Aligned API contracts and integration patterns with platform standards.',
      'Supported handover activities for testing, release, and operations teams.',
    ],
    metrics: [
      'Expanded event-driven coverage with Kafka and ActiveMQ notifications.',
      'Raised code quality visibility through SonarCloud and logging improvements.',
    ],
  },
  {
    id: 'signature-demo',
    title: 'Signature Demo',
    timeframe: 'Aug 2025',
    org: 'Personal Project',
    role: 'Backend Developer',
    teamSize: 'Team of 3',
    category: 'Platform',
    tagline:
      'Signature verification backend with customer uploads, SFTP sync, and maker-checker approval workflows.',
    highlights: [
      'Built Spring Boot APIs for signature upload, review, approval, rejection, and tracking flows.',
      'Integrated SFTP sync for exchanging newly created signatures with file-based systems.',
      'Modeled maker-checker approval orchestration with Camunda 8 and Zeebe.',
      'Secured REST endpoints with Spring Security, validation, and OpenAPI documentation.',
      'Persisted application, signature, and workflow state in Oracle Database.',
      'Added optional AI-based signature similarity checks when the external service is available.',
    ],
    tech: [
      'Java 17',
      'Spring Boot',
      'Spring Security',
      'Spring Data JPA',
      'REST API',
      'Oracle DB',
      'Camunda 8',
      'Zeebe',
      'SFTP',
      'OpenAPI',
      'Docker Compose',
      'Maven',
    ],
    links: {
      live: '',
      source: 'https://github.com/tienhuynh-tn/signature-demo-be/',
      caseStudy: '',
    },
    image: {
      src: signatureDemoImg,
      alt: 'Signature verification workflow illustration',
    },
    featured: true,
    responsibilities: [
      'Designed backend workflows for customer signature intake and staff approval operations.',
      'Configured Oracle, SFTP, and Camunda services for the local demo stack.',
      'Documented setup and API usage for running the backend locally.',
    ],
    metrics: [
      'Covers the full flow from customer upload through manager decision.',
      'Combines file sync, workflow orchestration, persistence, and API documentation in one backend demo.',
    ],
  },
  {
    id: 'social-toilet-map',
    title: 'Social Toilet Map',
    timeframe: 'Feb 2023 – Aug 2023',
    org: 'FPT University',
    role: 'Backend Developer / Database Designer',
    teamSize: 'Team of 5',
    category: 'University',
    tagline:
      'Map-based app helping people find nearby public toilets with host management and operational insights.',
    highlights: [
      'Built the backend for nearby toilet discovery and direction-based search flows.',
      'Designed host and manager functions for availability, amenities, and location updates.',
      'Implemented multi-role permissions for visitors, hosts, and management staff.',
      'Added analytics and notification support for operational visibility.',
      'Designed the database model for map, facility, and feedback data.',
      'Supported team delivery through API integration and testing collaboration.',
    ],
    tech: [
      'Java',
      'Spring Boot',
      'REST API',
      'Azure',
      'SQL',
      'Database Design',
      'Role-Based Access',
      'Maps',
      'Git',
    ],
    links: {
      live: '',
      source: '',
      caseStudy: '',
    },
    image: {
      src: mapImg,
      alt: 'Map service illustration',
    },
    featured: true,
    responsibilities: [
      'Owned backend services and database design for the capstone team.',
      'Designed access control and management-side workflows.',
      'Worked with frontend teammates on API integration and validation.',
    ],
    metrics: [
      'Delivered a graduation capstone with mapped discovery and host operations support.',
      'Covered both consumer search flows and administrative management scenarios.',
    ],
  },
  {
    id: 'eat-clean-menu-app',
    title: 'Eat Clean Menu App',
    timeframe: 'Sep 2022 – Mar 2023',
    org: 'FPT University',
    role: 'Backend Developer / Database Designer',
    teamSize: 'Team of 4',
    category: 'Mobile',
    tagline:
      'Personalized clean-menu recommender using BMI + preferences with ingredient planning.',
    highlights: [
      'Built recommendation APIs using BMI data, user goals, and food preferences.',
      'Designed database structures for menus, ingredients, nutrition data, and user profiles.',
      'Supported ingredient planning workflows for meal preparation scenarios.',
      'Implemented secure authentication with JWT for mobile access.',
      'Published and documented backend APIs for smoother frontend integration.',
      'Deployed services to Azure App Service and connected supporting Firebase features.',
    ],
    tech: [
      'Java',
      'Spring Boot',
      'REST API',
      'React Native',
      'SQL Server',
      'Azure App Service',
      'Firebase',
      'JWT',
      'Swagger',
      'Git',
    ],
    links: {
      live: '',
      source: '',
      caseStudy: '',
    },
    image: {
      src: mobileImg,
      alt: 'Nutrition mobile app illustration',
    },
    responsibilities: [
      'Implemented recommendation and account APIs for the mobile application.',
      'Maintained the database schema and deployment configuration.',
    ],
  },
  {
    id: 'viral-music-web',
    title: 'Viral Music Web',
    timeframe: 'Jan 2023 – Mar 2023',
    org: 'FPT University',
    role: 'Backend Developer / Database Designer',
    teamSize: 'Team of 4',
    category: 'Web',
    tagline:
      'Web app aggregating viral music with secure storage and API-driven architecture.',
    highlights: [
      'Built backend APIs for music aggregation, listing, and retrieval workflows.',
      'Designed database entities for tracks, categories, and user interactions.',
      'Implemented secure data persistence with Entity Framework and SQL Server.',
      'Documented APIs with Swagger to support frontend development.',
      'Integrated cloud storage for media-related content management.',
      'Collaborated on a clean API-driven structure between frontend and backend layers.',
    ],
    tech: [
      'React',
      'C# .NET Core',
      'Entity Framework',
      'SQL Server',
      'REST API',
      'Cloud Storage',
      'Swagger',
      'Git',
    ],
    links: {
      live: '',
      source: '',
      caseStudy: '',
    },
    image: {
      src: webImg,
      alt: 'Music web platform illustration',
    },
  },
  {
    id: 'blood-donor-webapp',
    title: 'Blood Donor WebApp',
    timeframe: 'Sep 2022 – Nov 2022',
    org: 'FPT University',
    role: 'Backend Developer / Database Designer',
    teamSize: 'Team of 4',
    category: 'Web',
    tagline:
      'Platform connecting blood donors with donation centers for streamlined coordination.',
    highlights: [
      'Built backend workflows for donor registration and center coordination.',
      'Designed database models for donors, requests, appointments, and center records.',
      'Implemented core CRUD APIs and data validation for donation workflows.',
      'Supported a responsive web interface built with HTML, CSS, JavaScript, and Bootstrap.',
      'Used Entity Framework to simplify persistence and query handling.',
      'Collaborated on end-to-end testing of donor and center scenarios.',
    ],
    tech: [
      'HTML',
      'CSS',
      'JavaScript',
      'Bootstrap',
      'C# .NET Core',
      'Entity Framework',
      'SQL Server',
      'CRUD API',
      'Git',
    ],
    links: {
      live: '',
      source: '',
      caseStudy: '',
    },
    image: {
      src: healthImg,
      alt: 'Health platform illustration',
    },
  },
  {
    id: 'co-tam-website-and-android-mobile-app',
    title: 'Cô Tấm Website + Android Mobile App',
    timeframe: 'Sep 2022 – Nov 2022',
    org: 'FPT University',
    role: 'Backend Developer / Database Designer',
    teamSize: 'Team of 5',
    category: 'Mobile',
    tagline:
      'Domestic help booking platform with admin web portal and customer/worker mobile apps.',
    highlights: [
      'Built backend services for booking, user profiles, and service management flows.',
      'Designed shared data models for admin web and customer or worker mobile apps.',
      'Implemented authentication with OAuth2 and JWT for multiple client types.',
      'Supported Azure App Service deployment and Firebase-backed mobile features.',
      'Documented service APIs with Swagger for team-wide integration.',
      'Coordinated database design for bookings, workers, customers, and service catalogs.',
    ],
    tech: [
      'React',
      'Flutter',
      'C# .NET Core',
      'REST API',
      'SQL Server',
      'Azure App Service',
      'Firebase',
      'OAuth2',
      'JWT',
      'Swagger',
      'Git',
    ],
    links: {
      live: '',
      source: '',
      caseStudy: '',
    },
    image: {
      src: mobileImg,
      alt: 'Service booking mobile app illustration',
    },
  },
  {
    id: 'publish-graduation-capstone-webapp',
    title: 'Publish Graduation Capstone WebApp',
    timeframe: 'Jan 2022 – Apr 2022',
    org: 'FPT University',
    role: 'Backend Developer / Database Designer',
    teamSize: 'Team of 4',
    category: 'University',
    tagline:
      'Capstone management web system for topics, submissions, and evaluation workflows.',
    highlights: [
      'Built backend flows for topic registration, approvals, submissions, and evaluation tracking.',
      'Designed relational data structures for capstone topics, teams, mentors, and grading artifacts.',
      'Implemented REST endpoints for role-based capstone management actions.',
      'Applied OAuth-secured access to protect student and faculty workflows.',
      'Supported MVC-based application structure for maintainable delivery.',
      'Helped test end-to-end academic management scenarios across the system.',
    ],
    tech: [
      'Java',
      'REST API',
      'SQL Server',
      'OAuth',
      'MVC',
      'Database Design',
      'Academic Workflow',
      'Git',
    ],
    links: {
      live: '',
      source: '',
      caseStudy: '',
    },
    image: {
      src: universityImg,
      alt: 'Academic dashboard illustration',
    },
  },
  {
    id: 'sleepy-3-friends-clock',
    title: 'SEF Project - Sleepy 3 Friends Clock',
    timeframe: 'Sep 2021 – Oct 2021',
    org: 'FPT University',
    role: 'Embedded/IoT Student Project',
    teamSize: 'Team of 3',
    category: 'IoT',
    tagline:
      'Arduino-based clock prototype built with C and basic IoT integration.',
    highlights: [
      'Built a clock prototype on Arduino hardware using C.',
      'Implemented core timekeeping and device interaction logic for the project demo.',
      'Explored basic IoT integration concepts as part of the system setup.',
      'Worked through low-level hardware interaction and debugging tasks.',
      'Collaborated on assembling, testing, and validating the prototype behavior.',
      'Delivered an early-stage embedded system project within a short academic schedule.',
    ],
    tech: ['C', 'Arduino', 'Embedded Systems', 'IoT', 'Hardware Prototype'],
    links: {
      live: '',
      source: '',
      caseStudy: '',
    },
    image: {
      src: iotImg,
      alt: 'IoT hardware clock illustration',
    },
  },
]

export const featuredProjects = allProjects
  .filter((project) => project.featured)
  .sort((left, right) => getProjectSortTime(right.timeframe) - getProjectSortTime(left.timeframe))
  .slice(0, 3)
export const projects = allProjects
